name: geno-bioinfo-r
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  # Jupyter dependencies
  - jupyterhub>=1.5,<2
  - jupyterlab>=3.2,<4
  - jupyter-resource-usage
  - jupyterlab-topbar
  - jupyterlab-topbar-text
  - jupyterlab-system-monitor
  - nodejs
  - pip
  - gfortran_linux-64
  # Jupyter archive
  # https://github.com/jupyterlab-contrib/jupyter-archive
  - jupyter-archive
  # Jupyter git
  # https://github.com/jupyterlab/jupyterlab-git
  - jupyterlab-git
  # R environment
  - r-irkernel
  - r-base>=4.1.0
  - r-rcpp
  - r-tidyverse=1.3.1.9000
  - r-factominer
  - r-factoextra
  - r-dt
  - r-igraph
  - r-polyclip
  #- bioconductor-clusterprofiler
  #- bioconductor-complexheatmap
